<?
# CONSTANTES UPLOADS PARTICULARES
define('DIR_UPLOADS_NOTICIAS',DIR_UPLOADS.'noticias/');
define('DIR_UPLOADS_SLIDESHOWS',DIR_UPLOADS.'slideshows/');
define('DIR_UPLOADS_PRODUCTOS',DIR_UPLOADS.'productos/');
?>